name: CI
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.0, 1.4]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: x64
      - uses: julia-actions/julia-buildpkg@latest
      # remove this after 2.0
      - name: test package
        run: julia -e 'using Pkg; Pkg.test(coverage=true, julia_args=["color=yes", "check-bounds=yes", "depwarn=no", "project"])'
      # uncomment after 2.0
      # - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-uploadcodecov@latest
        if: ${{ matrix.julia-version == '1.4' && matrix.os =='ubuntu-latest' }}
